### ISSUE TITLE
Add command line option for communications bug workaround

### ISSUE THREAD

**Issue by jweber-ice** [WIPACrepo/stf#106]
Several test configurations have encountered repeatable communications issues, e.g. Issue #80. Users work around the problem by commenting out lines of STF code. This solution requires tribal knowledge and is difficult to track in configuration.

Instead provide a command line option which functionally disables the same code, and records the configuration change in tests results. This enables users to use pristine STF release code, and provides a record of the configuration change.

**Comment by jweber-ice** [comment]
This is not a solution for Issue #80 which is still not yet resolved.

**Comment by csburreson** [comment]
this is very sensible and sounds straight forward. I'll try to get to this in the next day or two

**Comment by jweber-ice** [comment]
There has been negative feedback about this capability:
* It allows a test communications issue to continue unresolved, with a bandaid fix.
* This capability allows breaking the STF requirement to always start each test from a known configuration.
* This capability discards MCU error log events.

Given these, I recommend we implement this capability as an undocumented option, with an advisor warning when enabled.

**Comment by jweber-ice** [comment]
Commit 3347e939a5cf5e3f6d4522c588a93a8c5d26455e . I am unable to get the help message to display from either:
`
$ python3 test.py -h
`
or from
`
$python3 runset.py  -h
`

which is OK since this option is a last resort and not recommended.
