### ISSUE TITLE
use `flashID` for htf dut_id and save in output

### ISSUE THREAD

**Issue by csburreson** [WIPACrepo/stf#30]
fixed in 1.2.

Just a note that we're using the flashID for the device ID for testing purposes (for now)

**Comment by jweber-ice** [comment]
class IcebootSessionCmd has a _flashID()_ method which returns the motherboard SPI flash hardware ID. Sample output:
`c42570cc1482 `

Currently this is the only available unique hardware ID, but there will be more coming:
FPGA ID
EEPROM board ID
DOM ID
others ...

The STF should include the hardware IDs in results as these become available.

**Comment by jweber-ice** [comment]
Just updated FPGA firmware release to 0xfe which enables the Iceboot _printFPGAChipID_ command to print the FPGA unique chip ID. Iceboot usage:
```
> printFPGAChipID
printFPGAChipID
0x00f1418418a3fe17
```

If FPGA is not loaded, or too old, output will be:
```
> printFPGAChipID
printFPGAChipID
0xffffffffffffffff
```

There is not yet a IcebootSessionCmd convenience method for this command, but one code be added.

Please add _printFPGAChipID_ output to results.
