### ISSUE TITLE
support for running testsets across multiple devices simulataneously

### ISSUE THREAD

**Issue by csburreson** [WIPACrepo/stf#31]
should be able to run tests and sets of tests across multiple devices in parallel.

This can be accomplished with multithreading (IF I can ensure tests are CREATED ahead of time and EXECUTED in child threads)

This could also potentially be accomplished with multiple child processes? 

Currently this is *sort of* working but i might be hitting an issue with thread safety; openhtf code warns NOT to create Test() objects outside of the main process thread :/

If I can get a Plug-based iceboot_session for HTF that can *wait* to acquire session until EXECUTE is called this should be fine; the test can be defined in one function (called during setconfig initialization or right after) and the session can be created upon execute.

Maybe it's easiest to redefine testclasses MainboardTest to have multiple self.test objects... or like self.test (or self.instances) is a dict of 'name' -> 'args, evs, conns'? 

Like:
self.test['base'] points to some record containing defined test and conn settings? or maybe MainboardTest objects are instantiated with connection settings, and we have one per device which can have its execute method called many times?? 

is it possible to call the execute method on a single class with different args at the same time? or do I need a clone of this for each device? maybe we should wait 'til 1.3 to support this :/

**Comment by jweber-ice** [comment]
HALT testing did indeed successfully run 2 sunsets in parallel:

> python3 ./runset.py HALT --iceboot_host=haltstf  --iceboot_port=5012
> python3 ./runset.py HALT --iceboot_host=haltstf  --iceboot_port=5011

**Comment by jweber-ice** [comment]
Closing this issue because multiple run sets can be excited as separate Python processes from the shell. However CBurreson would prefer to run multiple run sets from within the framework as an improvement.
