### ISSUE TITLE
UnicodeDecodeError exception killed STF framework

### ISSUE THREAD

**Issue by jweber-ice** [WIPACrepo/stf#51]
Exception in FPGATimestamping-channel-1 test killed entire runset. This occurred after STF commit "1.2.2 to address socket/comms issues discovered during HALT'

Results location: cobalt:/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-1-v1.0_degg-0c52f6f87fbd.json

It appears that an occurrence of the exception in the _tearDown_ phase can kill the entire run set.

**Comment by csburreson** [comment]
note to self: harden setup/teardown and the fn that grabs the board info (prior to test phase)

**Comment by jweber-ice** [comment]
After encountering the exception, the console output for the sunset showed each successive test also encountering exceptions:
```
INFO >>> Running FPGATimestamping:channel-1
New IceBoot session: FPGA version ffff Software version 1b beccc83 Tue Feb 11 16:52:17 2020 -0600
INFO >>> checking flash for /home/jweber/git/stf/data/degg_fw_v0x101.rbf ... status=ok)
INFO >>> checkCommsAndFirmware -> configuring fw file from flash: degg_fw_v0x101.rbf)
:ERROR
  exception type: UnicodeDecodeError
INFO >>> Finished FPGATimestamping
INFO >>> Running Interlock:base
INFO >>> Exception raised during test Interlock:base
INFO >>> Running LightSensor:lights-on
INFO >>> Exception raised during test LightSensor:lights-on
INFO >>> Running MagnetometerSensor:base
INFO >>> Exception raised during test MagnetometerSensor:base
INFO >>> Running PowerLVS:base
INFO >>> Exception raised during test PowerLVS:base
INFO >>> Running PowerRails:base
<kill test here>
```

However the report/summary.txt shows the run set stopping at the exception:
```
>>> Runset report for HALT

Runset Name              :  HALT
Device Type              :  degg
Device ID                :  0c52f6f87fbd
FPGA ChipID              :  0x00f1440a4072100e
Date run                 :  2020-02-14 21:42:27.751000
Station                  :  fc30
STF Version              :  1.2.2
FPGA Version             :  0x101
Iceboot                  :  v27 - build beccc83 Tue Feb 11 16:52:17 2020 -0600

FAIL   AccelerometerSensor v1.0
PASS   ADCComms v1.0
PASS   ADCComms v1.0
PASS   ADCNoiseLevel v1.0
PASS   ADCNoiseLevel v1.0
ERROR   ADCTestPatterns v1.0
PASS   ADCTestPatterns v1.0
PASS   BaselineStability v1.0
PASS   BaselineStability v1.0
PASS   DACScan v1.0
PASS   DPRAM v1.0
FAIL   FEPulserCharge v1.0
PASS   FEPulserCharge v1.0
PASS   FEPulserHeight v1.0
PASS   FEPulserHeight v1.0
PASS   FEPulserLinearity v1.0
PASS   FEPulserLinearity v1.0
PASS   FEPulserWidth v1.0
PASS   FEPulserWidth v1.0
PASS   Flash v1.0
PASS   FPGAMemTest v1.0
FAIL   FPGATimestamping v1.0
ERROR   FPGATimestamping v1.0
```

Regardless, the run set was broken at the time of the exception, and did not recover.

**Comment by jweber-ice** [comment]
A similar exception killed the run set:
cobalt:$ less /data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_210011/degg-0c52f6f87fbd/BaselineStability-channel-1-v1.0_degg-0c52f6f87fbd.json

**Comment by csburreson** [comment]
<img width="1854" alt="Screen Shot 2020-02-25 at 09 42 00" src="https://user-images.githubusercontent.com/7819417/75266352-d573f700-57b7-11ea-90ed-e570342e4e1a.png">

Here's an example of the framework recovering from a UCD during teardown. Hopefully this issue stays dead.
