### ISSUE TITLE
UnicodeDecodeError killed test

### ISSUE THREAD

**Issue by jweber-ice** [WIPACrepo/stf#53]
Exceptions killed current test (but did not kill parent run set):

cobalt: /data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_195619/degg-0c52f6f87fbd/DACScan-base-v1.0_degg-0c52f6f87fbd.json

cobalt:/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/ADCTestPatterns-channel-0-v1.0_degg-0c52f6f87fbd.json

Exceptions occurred in phase _run_test_.

This issue is similar to issue #51 . In issue #51 the exceptions occurred in phase _tearDown_ and killed the entire run set

**Comment by csburreson** [comment]
related to #59 

Should hammer out a policy of retrying tests on known failure modes; this almost the same as #51 and should be handled quite similarly

**Comment by csburreson** [comment]
first stab at this didn't work too well. I should be able to create a wrapper for this... would like to include in v1.3

**Comment by jweber-ice** [comment]
These errors have not been seen for months.
