### ISSUE TITLE
HALT FPGATimestamping measurement validation errors

### ISSUE THREAD

**Issue by jweber-ice** [WIPACrepo/stf#58]
Though most HALT FPGATimestamping tests passed, several failed. Revisit test pass/fail criteria.

**Comment by jweber-ice** [comment]
Test results in cobalt.icecube.wisc.edu:/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_*

```
$ find /data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_* -name 'FPGATime*' | xargs grep -l -w -e FAIL  | xargs grep -A5 -e period_diff -e domclock_diff

/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_155627/degg-2f8c8eef6792/FPGATimestamping-channel-0-v1.0_degg-2f8c8eef6792.json:                "period_diff": {
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_155627/degg-2f8c8eef6792/FPGATimestamping-channel-0-v1.0_degg-2f8c8eef6792.json:                    "name": "period_diff",
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_155627/degg-2f8c8eef6792/FPGATimestamping-channel-0-v1.0_degg-2f8c8eef6792.json-                    "outcome": "FAIL",
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_155627/degg-2f8c8eef6792/FPGATimestamping-channel-0-v1.0_degg-2f8c8eef6792.json-                    "validators": [
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_155627/degg-2f8c8eef6792/FPGATimestamping-channel-0-v1.0_degg-2f8c8eef6792.json-                        "-0.005 <= x <= 0.005"
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_155627/degg-2f8c8eef6792/FPGATimestamping-channel-0-v1.0_degg-2f8c8eef6792.json-                    ],
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_155627/degg-2f8c8eef6792/FPGATimestamping-channel-0-v1.0_degg-2f8c8eef6792.json-                    "measured_value": 0.18379638704492285

/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-0-v1.0_degg-0c52f6f87fbd.json:                "period_diff": {
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-0-v1.0_degg-0c52f6f87fbd.json:                    "name": "period_diff",
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-0-v1.0_degg-0c52f6f87fbd.json-                    "outcome": "FAIL",
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-0-v1.0_degg-0c52f6f87fbd.json-                    "validators": [
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-0-v1.0_degg-0c52f6f87fbd.json-                        "-0.005 <= x <= 0.005"
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-0-v1.0_degg-0c52f6f87fbd.json-                    ],
/data/exp/IceCubeUpgrade/commissioning/stf/halt/HALT/2020.02.14_214218/degg-0c52f6f87fbd/FPGATimestamping-channel-0-v1.0_degg-0c52f6f87fbd.json-                    "measured_value": -0.0075086863831828055
```

**Comment by jweber-ice** [comment]
2 out of 50 tests run for HALT failed. Looking into the issue deeper, the "reference" clock used for checking FPGA timestamps is the python script host computer time. Unfortunately, this clock is very difficult to use for precision time stamping:
* The host OS may swap the python process in and out
* The host OS may respond to other interrupts
* The host OS may be running a NTP client, which adjusts the clock
etc.

Candidate options to continue using host reference clock:
* develop an algorithm which detects above events, and retries clock reads
* average the value from a set of host clock reads
* widen the tolerance window of FPGA timestamp to host clock

Or use a different DOM clock, perhaps an independent crystal. JBraun may have more info.

**Comment by atfienberg** [comment]
What exactly is this test intended to measure? As written, it essentially validates that the FPGA clock is operating near 60 MHz, which is the expected frequency. Evidently using the host computer clock is not a robust way to achieve this validation.

The FPGA clock frequency is determined by the oscillator that feeds the FPGA and also the MCU. For a meaningful test, we need to compare to a clock that isn't fed by that same oscillator.  

It is possible this test is unnecessary at the level 0 stage of testing because an incorrect FPGA clock would lead to other tests failures (e.g. the FE pulser width test). The sample rate tests planned for level 1 would then catch any clock issues not detected at level 0.

**Comment by jweber-ice** [comment]
commit 824a6674
