### ISSUE TITLE
Add git version hash id to test metadata

### ISSUE THREAD

**Issue by jweber-ice** [WIPACrepo/stf#91]
It can be difficult to look at test results and determine the STF configuration. For example, today Chiba reverted to an older STF which uses the same version 1.3.1 as today, and it was not possible to discover the reversion from test results. Further, test authors may change the test case code or expected values, which also escape the hard-coded STF version.

Add code to STF which saves the current git version hash to the test results. For example, the STM32Workspace code uses this [script](https://github.com/WIPACrepo/STM32Workspace/blob/master/stm-common/generate-git-version.sh) to place the current git version hash into compiled C-code. An Python interpreted solution should be simpler.

**Comment by mxmeier** [comment]
This can be done quite easily with gitpython. E.g.:

```
import os
import git


def get_git_infos():
    try:
        repo = git.Repo(path=os.getcwd(), search_parent_directories=True)
    except git.InvalidGitRepositoryError:
        return None, None, None, None, False
    try:
        active_branch = str(repo.active_branch.name)
    except TypeError:
        active_branch = 'DETACHED'
    sha = str(repo.head.object.hexsha)
    short_sha = str(repo.git.rev_parse(sha, short=7))
    try:
        origin = str(repo.git.execute(['git',
                                       'config',
                                       '--get',
                                       'remote.origin.url']))
    except git.exc.GitCommandError:
        origin = None
    uncommitted_changes = repo.is_dirty()
    return active_branch, short_sha, sha, origin, uncommitted_changes


active_branch, short_sha, sha, origin, uncommitted_changes = get_git_infos()


if __name__ == '__main__':
    print(f'Active branch: {active_branch}')
    print(f'Short SHA: {short_sha}')
    print(f'SHA: {sha}')
    print(f'Origin: {origin}')
    print(f'Uncommitted changes: {uncommitted_changes}')
```

**Comment by jweber-ice** [comment]
Hey Max, Thanks for reviewing the STF issues, and offering a suggestion. We are trying to minimize the dependencies when installing STF. Each new dependency adds a complexity to the STF installation, support, possible interactions, etc. So my preference for a Git API is that users do not have to install more packages to use it. Installing more packages can considered if that is the only way to achieve the needed functionality. Looking through the Python3 [standard library](https://docs.python.org/3/library/index.html), it looks like gitpython is not installed by default. I confirmed this on my CentOS8 and FedoraCore30 hosts. So I am inclined to first try to extract the local git hash using native Python. If that's "hard" I would next look to import git python. Thanks again for your input.

**Comment by mxmeier** [comment]
I see, this restriction makes a lot of sense. I found that numpy is using this function, only relying on the standard library packages `os` and `subprocess` in their setup.py.

```
# Return the git revision as a string
def git_version():
    def _minimal_ext_cmd(cmd):
        # construct minimal environment
        env = {}
        for k in ['SYSTEMROOT', 'PATH', 'HOME']:
            v = os.environ.get(k)
            if v is not None:
                env[k] = v
        # LANGUAGE is used on win32
        env['LANGUAGE'] = 'C'
        env['LANG'] = 'C'
        env['LC_ALL'] = 'C'
        out = subprocess.check_output(cmd, stderr=subprocess.STDOUT, env=env)
        return out

    try:
        out = _minimal_ext_cmd(['git', 'rev-parse', 'HEAD'])
        GIT_REVISION = out.strip().decode('ascii')
    except (subprocess.SubprocessError, OSError):
        GIT_REVISION = "Unknown"

    if not GIT_REVISION:
        # this shouldn't happen but apparently can (see gh-8512)
        GIT_REVISION = "Unknown"

    return GIT_REVISION
```

My guess is that without using a non-standard python package, its necessary to use `subprocess`.

**Comment by jweber-ice** [comment]
Commit. a8f904771ab9a0b8ae5005506a8421bcbf7e24d5
